<?php
/**
 * Loghound — what removing Loghound means, in one place.
 *
 * THE BOUNDARY, STATED ONCE. Everything Loghound created goes: the two indexes on the
 * platform, the configuration, everything under `var/`, the systemd units and both timers,
 * the command links, the service user, the FPM pool it created, the vhost it created, any
 * logrotate snippet or cron entry, and the install tree. Afterwards it should be as though
 * Loghound had never existed.
 *
 * WHAT IS NEVER TOUCHED, and this half matters as much as the other:
 *
 *   - THE OPERATOR'S ACCESS LOG FILES. They are the web server's, they existed before
 *     Loghound, and they are still written after it. Loghound has never written to one and an
 *     uninstall does not change that.
 *   - THE `LogFormat` LINE the operator added to their own vhost on Loghound's instruction. It
 *     lives in a file Loghound does not own, so it stays, and the run says at the end that it
 *     is still there and is theirs to remove.
 *   - ANYTHING WHOSE PROVENANCE CANNOT BE PROVED. The uninstaller once deleted vhosts and FPM
 *     pools BY NAME, which would have destroyed a hand-written `loghound.conf` in a directory
 *     full of other people's sites. It now requires the `GENERATED by install/install.sh`
 *     banner inside the file and fails closed without it. The same reasoning applies to every
 *     other thing it removes: a link is ours because it points into this prefix, a tree is
 *     ours because it carries Loghound markers, an index is ours because its name derives from
 *     `solr.install_id` AND the account listing says the account holds it.
 *
 * ---------------------------------------------------------------------------------------
 * TWO FRONT ENDS, ONE LIST OF STEPS
 * ---------------------------------------------------------------------------------------
 * `install/install.sh --uninstall` does all of it; the panel does the part that does not need
 * root. STEPS below is the canonical order and the canonical wording, and both front ends use
 * it, so an operator watching a terminal and an operator watching the panel see the same run.
 * tests/test_uninstall.php asserts the shell script's own `step` lines are exactly this list,
 * in this order, because two copies of a list is how two front ends stop agreeing.
 *
 * THE PANEL CANNOT DO THE SYSTEM HALF, AND WILL NOT PRETEND TO. There is no `exec`,
 * `shell_exec`, `proc_open` or SSH anywhere in `src/`, `bin/` or `public/`; that is a published
 * property of this product and it is worth more than the convenience of a button that stops a
 * systemd unit. So the panel performs PANEL_STEPS, reports every other step as needing a
 * shell, names the one command that does it, and the run ends able to state both halves.
 *
 * @package Loghound
 * @license MIT
 */

declare(strict_types=1);

namespace Loghound\Setup;

use Loghound\Config;

final class Teardown
{
    /**
     * The teardown, in the order it happens, keyed by step id.
     *
     * THE ORDER IS LOAD BEARING AND IS THE INSTALLER'S. Units first, so nothing is writing to
     * `var/` or talking to Solr underneath the run. Indexes before the configuration, because
     * the API key that authorises the deletion lives in that configuration. The web server
     * before the FPM pool, so it stops routing to a socket that is about to disappear. The
     * service user last, because `userdel` refuses while the daemon it owns is running and
     * removing it earlier leaves a tree owned by an orphaned uid.
     *
     * @var array<string,string>
     */
    public const STEPS = [
        'services'  => 'Services and timers',
        'ownership' => 'Proving your account owns these indexes',
        'delete'    => 'Deleting the Loghound indexes',
        'absence'   => 'Confirming they are gone from your account',
        'webserver' => 'Web server configuration',
        'fpm'       => 'PHP-FPM pool',
        'links'     => 'Command links and scheduler fragments',
        'data'      => 'Credentials and local data',
        'tree'      => 'Install tree',
        'user'      => 'System user',
        'report'    => 'What was NOT removed',
    ];

    /**
     * The steps the panel performs itself.
     *
     * The three index steps, because they are authenticated HTTPS calls to the control plane
     * and need nothing but the API key. The local data, because those are files the panel owns
     * and writes every day. The report, because it is words — and because it is where a
     * panel-driven run removes the configuration, which it must do last: this application reads
     * that file on every request, so the run has to be able to finish first.
     *
     * @var array<int,string>
     */
    public const PANEL_STEPS = ['ownership', 'delete', 'absence', 'data', 'report'];

    /**
     * The word the operator has to type before any of this happens.
     *
     * A typed word rather than a second button, because the consequences above it are long and
     * the point is that they get read. It is compared case-insensitively after trimming, so an
     * operator who typed it with a trailing space is not told "no" for the wrong reason.
     */
    public const CONFIRM_WORD = 'DELETE EVERYTHING';

    /**
     * How long a confirmed teardown stays armed, in seconds.
     *
     * Fifteen minutes: long enough to read the card again and press the button, short enough
     * that a browser left open on a shared machine is not still holding permission to destroy
     * the installation an hour later. It is spent when the run starts, so this is a ceiling.
     */
    private const ARM_TTL = 900;

    /** Session key holding a confirmed, unspent teardown. */
    private const ARM_KEY = 'lh_teardown_armed';

    /**
     * Record that this browser has typed the word and produced a current second factor.
     *
     * THE ARM IS THE CONFIRMATION, AND IT LIVES IN THE SESSION AND NOWHERE ELSE. There is no
     * cookie, header, hidden field or URL parameter that carries it, so the proof cannot be
     * replayed from a link and cannot be forged by anything that can reach the endpoint. It is
     * separate from the job that does the work for one reason: the job endpoint is polled, and
     * a confirmation attached to a poll would be a confirmation that has to be re-presented, or
     * re-checked, on every one of them.
     */
    public static function arm(): void
    {
        \Loghound\Security::startSession();
        $_SESSION[self::ARM_KEY] = time();
    }

    /**
     * Is a confirmed teardown waiting to be started, without consuming it?
     *
     * Used by the card so it can render the run. Rendering must not spend the arm: a reload of
     * the page between confirming and starting would otherwise silently disarm it.
     */
    public static function isArmed(): bool
    {
        $at = $_SESSION[self::ARM_KEY] ?? null;

        return is_int($at) && $at > 0 && (time() - $at) <= self::ARM_TTL;
    }

    /**
     * Spend the arm, if this session holds one that is still good.
     *
     * ONE-TIME. Removed whether or not it was still valid, so an expired one cannot sit in a
     * session being re-tested and a valid one authorises exactly one run.
     */
    public static function spendArm(): bool
    {
        \Loghound\Security::startSession();

        $at = $_SESSION[self::ARM_KEY] ?? null;
        unset($_SESSION[self::ARM_KEY]);

        return is_int($at) && $at > 0 && (time() - $at) <= self::ARM_TTL;
    }

    /** Drop any arm this session holds, without spending it. */
    public static function disarm(): void
    {
        \Loghound\Security::startSession();
        unset($_SESSION[self::ARM_KEY]);
    }

    /** Session key recording that a run has been started from this browser. */
    private const RUNNING_KEY = 'lh_teardown_running';

    /**
     * How long a started run keeps the card showing the run rather than the confirmation.
     *
     * An hour, which is far longer than a teardown takes and is bounded so a session that
     * watched one fail does not show a stale progress panel for ever.
     */
    private const RUNNING_TTL = 3600;

    /**
     * Remember that this browser started a run.
     *
     * THE PROBLEM THIS SOLVES. The arm is spent the moment the run begins, so an operator who
     * reloaded the page mid-teardown used to be shown the confirmation form again — a form
     * asking whether to start something that was already running, on a page with no sign of the
     * operation in progress. This is what lets the card reattach to it instead.
     *
     * It authorises nothing. Only the arm does, and it is gone by the time this is set.
     */
    public static function markRunning(): void
    {
        \Loghound\Security::startSession();
        $_SESSION[self::RUNNING_KEY] = time();
    }

    /** Did this browser start a run recently enough to still be watching it? */
    public static function isRunning(): bool
    {
        $at = $_SESSION[self::RUNNING_KEY] ?? null;

        return is_int($at) && $at > 0 && (time() - $at) <= self::RUNNING_TTL;
    }

    /** The label of one step, by id. */
    public static function label(string $id): string
    {
        return self::STEPS[$id] ?? $id;
    }

    /** Is this a step the panel can carry out on its own? */
    public static function isPanelStep(string $id): bool
    {
        return in_array($id, self::PANEL_STEPS, true);
    }

    /**
     * Why a step the panel cannot do needs a shell, per step.
     *
     * Each sentence names the specific thing root is needed for, because "needs root" on its
     * own tells an operator nothing about what is still on their machine.
     *
     * @return array<string,string>
     */
    public static function shellOnlyReasons(): array
    {
        return [
            'services'  => 'Stopping and removing loghound-tail.service and both timers is a systemd '
                . 'operation and needs root. Until it is done the reader keeps running with the '
                . 'configuration it started with, and keeps trying to write to indexes that are '
                . 'being deleted.',
            'webserver' => 'Removing the vhost means writing in your web server\'s configuration '
                . 'directory and reloading the server, which needs root — and it is only removed at '
                . 'all if the file carries the GENERATED banner install.sh puts in the ones it wrote.',
            'fpm'       => 'The dedicated PHP-FPM pool and its socket belong to the pool manager, and '
                . 'retiring one means reloading php-fpm as root.',
            'links'     => 'The command links live in /usr/local/bin, and any cron or logrotate '
                . 'fragment lives in /etc. Both need root.',
            'tree'      => 'The install tree is usually owned by root, and removing it is the one step '
                . 'that takes the uninstaller away with it.',
            'user'      => 'Removing the service user and its adm membership is userdel and gpasswd, '
                . 'which need root, and it has to happen after everything it owns is gone.',
        ];
    }

    /**
     * What pressing the button costs, in specifics rather than a warning.
     *
     * Nobody should press this and then discover what it meant. The first row is the one the
     * confirmation exists for: an Opensolr index name is unique across the whole platform and
     * is never released, the data in it is gone, and a backup taken in Opensolr beforehand is
     * the only way to keep any of it — which is a separately billed feature and is therefore
     * stated as one rather than implied to be free.
     *
     * @return array<int,array{what:string,happens:string}>
     */
    public static function consequences(): array
    {
        return [
            [
                'what'    => 'Your two Loghound indexes, and every document in them',
                'happens' => 'Permanently deleted from your Opensolr account. Every hit and every '
                    . 'session Loghound has ever recorded goes with them. There is no undo, and '
                    . 'Opensolr index names are unique across the whole platform and are never '
                    . 'released, so neither name can ever be created again — by you or by anyone.',
            ],
            [
                'what'    => 'Keeping the data',
                'happens' => 'The only way is a backup taken in Opensolr BEFORE you press this. '
                    . 'Opensolr backups are a separately billed feature, so if you have not bought '
                    . 'one and taken it, there is no copy of this data anywhere and there will not '
                    . 'be one afterwards.',
            ],
            [
                'what'    => 'Nothing else on your Opensolr account',
                'happens' => 'Untouched. Only the two names this installation created are deleted, '
                    . 'only after they are derived from solr.install_id and match what is stored, '
                    . 'and only after the platform\'s own listing confirms your account holds them.',
            ],
            [
                'what'    => 'The configuration',
                'happens' => 'Deleted. config/loghound.php goes, with the Opensolr API key, the '
                    . 'beacon signing key, the address salt, any Solr password and your panel '
                    . 'password hash in it. Overwriting a file is not a guarantee on a '
                    . 'copy-on-write, journalling or snapshotted filesystem, or on any SSD, so '
                    . 'treat the API key as exposed and rotate it at opensolr.com.',
            ],
            [
                'what'    => 'Everything under var/',
                'happens' => 'Deleted. The state database, the reader\'s position in every log file, '
                    . 'open sessions, the quota cache, the setup token, signed-in panel sessions, '
                    . 'remembered browsers, recovery code hashes, the rate-limit ledgers and the '
                    . 'saved schema check.',
            ],
            [
                'what'    => 'Your access log files',
                'happens' => 'Untouched, as always. Loghound has never written to one, never '
                    . 'truncated one and never rotated one, and removing Loghound does not change '
                    . 'that. They are exactly as they were.',
            ],
            [
                'what'    => 'The LogFormat line you added to your own web server',
                'happens' => 'Left alone. It lives in a file Loghound does not own, so this will not '
                    . 'reach into it. It is harmless — it only changes what your web server writes '
                    . 'to its own logs — and it is yours to remove or keep.',
            ],
            [
                'what'    => 'The beacon tag on your website',
                'happens' => 'Only you can remove it. Until you take the <script> element out of '
                    . 'your templates, every page load asks a host that no longer answers.',
            ],
            [
                'what'    => 'The service, the timers, the vhost, the FPM pool and this install tree',
                'happens' => 'They need root, so the panel cannot remove them and does not pretend '
                    . 'to. The command that does is shown below, and it proves it wrote a file '
                    . 'before it deletes it.',
            ],
        ];
    }

    /**
     * Everything a panel-driven run deliberately leaves behind, as the closing report.
     *
     * An uninstaller that is silent about what it left is an uninstaller nobody can verify, so
     * this is rendered whether or not the operator asks for it.
     *
     * @return array<int,string>
     */
    public static function leftBehind(string $root): array
    {
        $out = [];
        foreach (self::STEPS as $id => $label) {
            if (self::isPanelStep($id)) {
                continue;
            }
            $out[] = $label . ' — ' . (self::shellOnlyReasons()[$id] ?? 'needs root.');
        }

        $out[] = 'Your access log files — never written to, never truncated, never rotated, and '
            . 'exactly as they were.';
        $out[] = 'The LogFormat line in your own web server configuration — still there, never '
            . 'touched, and yours to remove or keep.';
        $out[] = 'The beacon <script> tag in your site templates — only you can take it out.';
        $out[] = 'Your Opensolr API key — rotate it at opensolr.com if this box is being '
            . 'decommissioned, sold or handed to somebody else. Backups and snapshots of this '
            . 'disk were never touched.';
        $out[] = 'Anything you added by hand — a supervisor unit, a firewall rule, a reverse proxy '
            . 'entry, a monitoring check, a backup job, an entry in your own logrotate '
            . 'configuration. Run ' . self::shellCommand($root) . ' for the rest of what Loghound '
            . 'itself created.';

        return $out;
    }

    /** The command that finishes the job, with this installation's real path. */
    public static function shellCommand(string $root): string
    {
        return 'sudo ' . rtrim($root, '/') . '/install/uninstall.sh';
    }

    /** The one line that stops ingestion first, which is the honest thing to do before this. */
    public static function stopCommand(): string
    {
        return 'sudo systemctl stop loghound-tail.service loghound-score.timer loghound-retention.timer';
    }

    /**
     * Delete everything under `var/`, keeping the directory itself.
     *
     * THE DIRECTORY STAYS ON PURPOSE. The installer is what the operator lands on next, and the
     * first thing it does is mint a token into `var/`. On a normal installation the tree is
     * root-owned and only `var/` is writable by the service user, so removing `var/` would
     * leave the panel process unable to recreate it and the operator unable to reach the
     * installer at all. Emptying it achieves the whole of what the boundary asks for.
     *
     * THE READER'S CURSORS ARE THE POINT, not a side effect. `var/state.db` holds
     * `(dev, inode, offset)` per source. An uninstall that deleted the indexes and left those
     * behind would leave the daemon believing it had already read those bytes, so a rebuilt
     * index would hold only traffic from the moment of the rebuild onwards and the history
     * before it would be unreachable even though the files are still on disk.
     *
     * `$keep` NAMES THE FILES THE RUN IS STANDING ON. A panel-driven teardown is executed one
     * step per request, through a job whose progress lives in `var/panel-jobs.db` and whose
     * owner lives in a session file under `var/sessions`. A wipe that took those with it would
     * destroy the record of its own progress mid-run, and the operator would be told their
     * operation no longer exists on a machine that had just deleted its indexes. The closing
     * step removes what was kept; see Panel\Settings.
     *
     * @param array<int,string> $keep Basenames left alone, matched exactly.
     * @return array{removed:int,kept:array<int,string>,failed:array<int,string>}
     */
    public static function wipeState(Config $cfg, array $keep = []): array
    {
        $dir = self::ownVarDir($cfg);
        if ($dir === '' || !is_dir($dir)) {
            return ['removed' => 0, 'kept' => [], 'failed' => []];
        }

        $removed = 0;
        $kept    = [];
        $failed  = [];
        foreach (self::entries($dir) as $path) {
            $name = basename($path);
            if (in_array($name, $keep, true)) {
                $kept[] = $name;
                continue;
            }
            if (self::remove($path)) {
                $removed++;
            } else {
                $failed[] = $name;
            }
        }

        return ['removed' => $removed, 'kept' => $kept, 'failed' => $failed];
    }

    /**
     * Remove named entries that a previous wipe was told to keep.
     *
     * The other half of `$keep`. Called by the closing step of a panel run, once nothing is
     * standing on them any more.
     *
     * @param array<int,string> $names Basenames under `var/`.
     * @return array{removed:array<int,string>,failed:array<int,string>}
     */
    public static function wipeRemaining(Config $cfg, array $names): array
    {
        $dir = self::ownVarDir($cfg);
        if ($dir === '') {
            return ['removed' => [], 'failed' => []];
        }
        $removed = [];
        $failed  = [];

        foreach ($names as $name) {
            if (!is_string($name) || $name === '' || $name === '.' || $name === '..'
                || str_contains($name, '/')
            ) {
                continue;
            }
            $path = $dir . '/' . $name;
            if (!file_exists($path) && !is_link($path)) {
                continue;
            }
            if (self::remove($path)) {
                $removed[] = $name;
            } else {
                $failed[] = $name;
            }
        }

        return ['removed' => $removed, 'failed' => $failed];
    }

    /**
     * Make sure PHP still has somewhere to write this request's session.
     *
     * A panel-driven run empties `var/`, and on the shipped PHP-FPM pool `session.save_path` is
     * `var/sessions`. With the directory gone, PHP's write at shutdown fails silently and the
     * one-time setup grant this run just issued is lost — which locks the operator out of the
     * installer they are about to be sent to, on a machine whose configuration has just been
     * deleted. So the directory is recreated, empty, at 0700.
     *
     * This is not a hole in the boundary: what is recreated holds no Loghound data, and the one
     * file that lands in it afterwards is the operator's own session carrying that grant. The
     * shell uninstaller removes the tree and everything in it.
     *
     * `$path` DEFAULTS TO THE RUNNING PROCESS'S SAVE PATH and exists so the suite can exercise
     * this at all: session ini settings cannot be changed once output has been sent, which under
     * the CLI runner is always, so a test has no way to make `session_save_path()` say anything.
     * It is not a hole — the path is still refused unless it is inside the var directory this
     * configuration can prove it owns, so the only thing a caller can choose is which directory
     * under `var/` gets recreated.
     *
     * @return string The path, or '' when sessions are not stored under var/.
     */
    public static function ensureSessionDir(Config $cfg, ?string $path = null): string
    {
        $path = $path ?? (string) session_save_path();
        if ($path === '' || str_contains($path, ';')) {
            return '';
        }

        $var = self::ownVarDir($cfg);
        if ($var === '' || !str_starts_with($path, $var . '/')) {
            return '';
        }
        if (!is_dir($path) && !@mkdir($path, 0700, true) && !is_dir($path)) {
            return '';
        }

        return $path;
    }

    /**
     * Delete the configuration and every sibling that holds a copy of its secrets.
     *
     * `config/.loghound.*.tmp` is the same file mid-write: Config::save() writes a private temp
     * file and renames it, so a crash between the two leaves a complete second copy of every
     * secret. `config/tls-*.key` is the self-signed private key install.sh generated. Neither
     * is hypothetical and neither is covered by removing one named file.
     *
     * LAST, ALWAYS. The API key that authorises the index deletion lives in here; purge first
     * and the operator is left with two orphaned indexes they can no longer name from this box.
     *
     * @return array{removed:array<int,string>,failed:array<int,string>}
     */
    public static function wipeConfig(Config $cfg): array
    {
        $path = $cfg->path();
        $dir  = dirname($path);

        if (self::ownVarDir($cfg) === '') {
            return ['removed' => [], 'failed' => [basename($path)]];
        }

        $targets = [$path];
        foreach ([$dir . '/.loghound.*.tmp', $dir . '/tls-*.key'] as $pattern) {
            foreach (glob($pattern) ?: [] as $extra) {
                $targets[] = $extra;
            }
        }

        $removed = [];
        $failed  = [];
        foreach ($targets as $target) {
            if (!file_exists($target)) {
                continue;
            }
            if (self::remove($target)) {
                $removed[] = basename($target);
            } else {
                $failed[] = basename($target);
            }
        }

        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate($path, true);
        }

        return ['removed' => $removed, 'failed' => $failed];
    }

    /**
     * The `var/` that belongs to THIS configuration, or '' when it cannot be proved to.
     *
     * THE FAILURE THIS FAILS CLOSED ON. Config::varDir() answers `<root>/var` when the
     * configuration sits in `<root>/config/`, and falls back to the var directory of the
     * INSTALLED TREE for any other layout — which is right for a Config that was never loaded
     * from a real file, and catastrophic for a caller whose next move is to delete everything
     * in the directory it names. A stray Config object must not be able to empty the running
     * installation's state.
     *
     * So the relationship is required rather than assumed: the configuration lives in a
     * directory called `config`, and the var directory is its sibling. That is the shape every
     * Loghound installation has, and anything else here is a caller that has not proved which
     * installation it is talking about.
     */
    private static function ownVarDir(Config $cfg): string
    {
        $configDir = dirname($cfg->path());
        if (basename($configDir) !== 'config') {
            return '';
        }

        $expected = dirname($configDir) . '/var';

        return rtrim($cfg->varDir(), '/') === $expected ? $expected : '';
    }

    /**
     * Direct children of a directory, symlinks included and never followed.
     *
     * @return array<int,string>
     */
    private static function entries(string $dir): array
    {
        $out = [];
        foreach ((array) scandir($dir) as $entry) {
            if ($entry === '.' || $entry === '..' || !is_string($entry)) {
                continue;
            }
            $out[] = $dir . '/' . $entry;
        }

        return $out;
    }

    /**
     * Remove one path, recursing into a real directory and never through a symlink.
     *
     * A symlink is unlinked, not followed: `var/sessions` pointed somewhere else by an operator
     * — or by anything that can write in `var/` — must not turn an empty-the-directory into a
     * delete of whatever it aims at.
     */
    private static function remove(string $path): bool
    {
        if (is_link($path)) {
            return @unlink($path);
        }
        if (is_dir($path)) {
            $ok = true;
            foreach (self::entries($path) as $child) {
                $ok = self::remove($child) && $ok;
            }

            return @rmdir($path) && $ok;
        }

        return @unlink($path);
    }
}
