<?php
/**
 * Loghound — panel preview helper (development only).
 *
 * The panel authenticates every request and fails closed: with no auth configured it
 * refuses to serve at all, because an analytics dashboard left open on the internet is a
 * data breach. That is correct, and this script does not weaken it — there is no auth
 * bypass anywhere in the panel, not for localhost, not for demo mode, not for anything.
 *
 * What it does instead is write a throwaway configuration with HTTP Basic auth switched
 * on and demo data enabled, so a developer can look at the panel in thirty seconds
 * without provisioning Solr.
 *
 *   php tools/panel-preview.php
 *   php -S 127.0.0.1:8099 -t public
 *   open http://127.0.0.1:8099/     (credentials are printed below)
 *
 * It refuses to overwrite an existing config, because the real one holds the Opensolr API
 * key and the beacon HMAC secret and losing those to a convenience script would be a
 * genuinely bad afternoon.
 *
 * @package Loghound
 * @license MIT
 */

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

$root = dirname(__DIR__);
$configPath = $root . '/config/loghound.php';
$force = in_array('--force', $argv, true);

if (is_file($configPath) && !$force) {
    fwrite(STDERR, "Refusing to overwrite an existing config: $configPath\n");
    fwrite(STDERR, "It may hold your Opensolr API key and beacon secret. Pass --force only if you are sure.\n");
    exit(1);
}

@mkdir($root . '/config', 0750, true);
@mkdir($root . '/var', 0750, true);

$password = bin2hex(random_bytes(6));

$config = [
    'site_name' => 'Loghound (preview)',
    'base_url'  => 'http://127.0.0.1:8099',
    'auth' => [
        'mode'          => 'basic',
        'user'          => 'loghound',
        'password_hash' => password_hash($password, PASSWORD_DEFAULT),
    ],
    'beacon' => ['enabled' => false, 'secret' => ''],
    'solr'   => [
        'mode'          => 'opensolr',
        'base_url'      => 'http://127.0.0.1:8983/solr',
        'hits_core'     => 'loghound_preview_hits',
        'sessions_core' => 'loghound_preview_sessions',
    ],
    'ui'     => ['demo' => true, 'timezone' => 'UTC'],
];

$php = "<?php\n"
    . "/**\n"
    . " * Loghound preview configuration — generated by tools/panel-preview.php.\n"
    . " * DEVELOPMENT ONLY. Delete this file before deploying anything.\n"
    . " */\n"
    . "if (PHP_SAPI !== 'cli' && !defined('LOGHOUND')) { exit; }\n\n"
    . 'return ' . var_export($config, true) . ";\n";

file_put_contents($configPath, $php);
chmod($configPath, 0640);

echo "Wrote $configPath\n\n";
echo "  php -S 127.0.0.1:8099 -t " . $root . "/public\n\n";
echo "  URL:      http://127.0.0.1:8099/\n";
echo "  User:     loghound\n";
echo "  Password: $password\n\n";
echo "Demo data is ON. Every page says so. Remove 'demo' => true from the 'ui' section\n";
echo "(or delete this config) to point the panel at a real Solr.\n";
